[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
[profile.release.build-override]
opt-level = 's'
incremental = false
codegen-units = 1
